# Generated by Django 4.0.3 on 2022-04-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=15)),
                ('your_email', models.CharField(max_length=20)),
                ('your_sub', models.CharField(max_length=15)),
                ('your_mess', models.CharField(max_length=15)),
            ],
        ),
    ]
